name: Checks

on:
  pull_request:

jobs:
  check:
    name: Check
    runs-on: linux
    steps:
      - uses: actions/checkout@v4
      - name: Use Node v24
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 24.x
      - run: npm ci
      - run: npm run check:all
